### ISSUE TITLE
Traduction de la page es6.md

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#10]
Je m'occupe de traduire la page es6.md et de proposer un pull request. J'utilise ce ticket pour suivre la progression. La page en question se trouve ici:

https://github.com/iojs/website/blob/master/content/fr/es6.md

**Comment by podefr** [comment]
Voici ma traduction pour la page es6.md: https://github.com/iojs/website/pull/154

N'hésitez pas à commenter si quelque chose sonne faux. Il peut y avoir aussi quelques fautes d'ortho/grammaire, je relirai à tête reposée. merci!

**Comment by podefr** [comment]
Mise à jour du pull request: https://github.com/iojs/website/pull/154, merci de relire une fois encore et de +1 si ça vous convient :)

**Comment by Nicolab** [comment]
J'ai commenté aux lignes concernées :)

**Comment by podefr** [comment]
PR merged! Merci pour vos reviews!
