### ISSUE TITLE
Traduction de la page faq.md

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#11]
Nous recherchons quelqu'un pour traduire la page faq.md qui se trouve ici:

https://github.com/iojs/website/blob/master/content/fr/faq.md

Il faudra soumettre un pull request avec la traduction une fois celle-ci faite.

Si vous souhaitez traduire cette page, merci de vous assigner ce ticket ;)

**Comment by yrezgui** [comment]
Je m'en occupe !

**Comment by yrezgui** [comment]
https://github.com/iojs/website/pull/141 Voilà un premier draft. J'ai pas pu enlever le label help wanted parce que je suis pas encore contributeur de ce repo (@podefr m'a renvoyé un mail mais j'ai rien reçu...)

**Comment by yrezgui** [comment]
Je viens d'enlever le label et j'attends une review de la pull-request par un autre membre de notre communauté francophone avant un merge

**Comment by podefr** [comment]
la traduction est à présent mergée sur master. Good job team!
