### ISSUE TITLE
Traduction de la page index.md

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#12]
Nous recherchons quelqu'un pour traduire la page index.md qui se trouve ici:

https://github.com/iojs/website/blob/master/content/fr/index.md

Il faudra soumettre un pull request avec la traduction une fois celle-ci faite.

Si vous souhaitez traduire cette page, merci de vous assigner ce ticket ;)

**Comment by bcabanes** [comment]
Je peux m'en charger!

**Comment by bcabanes** [comment]
https://github.com/iojs/website/pull/152 Voilà un premier draft. En attente de validation par d'autres membres de la communauté.

**Comment by podefr** [comment]
la traduction est à présent mergée sur master. Good job team!
