### ISSUE TITLE
Traduction de la page template.json

### ISSUE THREAD

**Issue by bentranter** [iojs/iojs-fr#14]
Comme mentionné ici (https://github.com/iojs/website/pull/141), quelqu'un a besoin de traduire `template.json`. Je me suis occupé, et je viens de proposer un pull request. Je pense que j'ai besoin de quelqu'un pour l'examiner avant qu'il puisse être fusionné. Le pull request se trouve ici: https://github.com/iojs/website/pull/149

**Comment by podefr** [comment]
Bien vu, merci!

J'ai posté quelques remarques.

**Comment by bentranter** [comment]
Merci @podefr, j'ai mis a jour le PR.

**Comment by podefr** [comment]
je ferme le ticket comme le pull request vient d'être mergé. Merci pour la traduction!
