### ISSUE TITLE
Création d'un glossaire.md pour faciliter la traduction en->fr de mots/expressions récurrents

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#15]
Hello,

Pour faciliter la traduction des documents en->fr, je me demandais si on ne devrait pas créer un glossaire qui contiendrait notre traduction "officielle" de mots et expressions courants. Ceci permettrait de conserver une forme de constance entre chaque document traduit, afin de donner l'impression qu'une seule et même personne s'occupe des traductions, un peu comme un style guide.

Par exemple:

release: on traduit ou on conserve le mot anglais? et quelle traduction?
runtime flag: option d'éxécution? 
staging/development/shipping: en phase d'acceptation/développement/livraison? Ou on garde les terms anglais?

qu'en pensez-vous?

**Comment by Nicolab** [comment]
Salut,

juste mon avis, parfois cela complique les choses de tout franciser, certaines traductions peuvent être ambigus. Des termes anglais récurrents sont souvent mieux connus que la francisation. 

Le glossaire est une excellente idée, il évite de se retrouver avec un coup _email_, ailleurs _courriel_. (pourriel, gratuiciel, etc toutes les tentatives de francisation).

**Comment by podefr** [comment]
Je ferme ce ticket, on peut continuer la discussion avec #21
