### ISSUE TITLE
Traduction de "io.js and a node.js Foundation"

### ISSUE THREAD

**Issue by yrezgui** [iojs/iojs-fr#17]
J'ai écrit un brouillon (besoin de reviews sur quelques tournures de phrases et traduction de mots techniques) : https://github.com/iojs/iojs-fr/pull/16

**Comment by podefr** [comment]
super trad' :) j'ai posté un commentaire sur le pull request

**Comment by podefr** [comment]
merci pour la trad + post sur medium!
