### ISSUE TITLE
Traducteur

### ISSUE THREAD

**Issue by Nicolab** [iojs/iojs-fr#18]
Bonjour à tous,

je crée cette issue pour rejoindre et aider la team FR :)
La demande est faite sur l'issue de [Mikeal](https://github.com/iojs/website/issues/125#issuecomment-73747763).

Accessoirement j'ai commencé un gros travail de traduction de l'API doc de Node il y a quelques mois (environ 70%). Ca peut accélérer les choses.

**Comment by podefr** [comment]
Je t'ai ajouté à la liste des contributeurs, ajoute-toi au Readme.md une fois membre et je fermerai ce ticket!

**Comment by Nicolab** [comment]
Ajouté, merci !
