### ISSUE TITLE
Quel service pour poster les articles traduits?

### ISSUE THREAD

**Issue by thaume** [iojs/iojs-fr#2]
Hello,

On part sur Medium pour poster les articles traduits?

**Comment by podefr** [comment]
Moi ça me va!

**Comment by thaume** [comment]
Let's go alors! Je créé le compte

**Comment by bcabanes** [comment]
Ca me va aussi!

**Comment by thaume** [comment]
Le profile medium https://medium.com/@iojs_fr ! La connexion se fait via twitter, on y a donc tous accès

**Comment by yrezgui** [comment]
C'est pas mieux que chaque contributeur écrie son article sous son propre compte et on ajoute l'ajoute l'article à une collection gérée par iojs_fr ?

**Comment by pierreinglebert** [comment]
Je ne pense pas car là il s'agit de traductions d'annonces officielles d'iojs, on parle au nom d'io.js pas au nom d'un des membre de la communauté.
