### ISSUE TITLE
Besoin d'une traduction pour la Roadmap

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#31]
Nous avons besoin d'une traduction pour le document suivant:

http://roadmap.iojs.org/
https://github.com/iojs/roadmap

Comme indiqué ici: 
https://github.com/iojs/roadmap/issues/18

"I'm thinking that the best thing to do is simply copy the index.html to a localization subfolder, translate it, and replace the references to relative ../ so that we don't have to copy all the assets. Translators should also add content to the slides about how to get involved in their language communities :)"

**Comment by yoannmoinet** [comment]
@cedced19 s'en est occupé sur cette [PR](https://github.com/iojs/roadmap/pull/26)
