### ISSUE TITLE
Traducteur?

### ISSUE THREAD

**Issue by snostorm** [iojs/iojs-fr#37]
Bonjour,

Je habite en France mais je apprends le français. Je travaille sur le groupe de site Web.

Merci!

**Comment by snostorm** [comment]
> I should still get involved with the "fr" group, regardless. I might not do a lot of serious translation, but it would be nice to help review/ be involved. iojs/iojs-fr#37

**Comment by yrezgui** [comment]
Bonjour l'ami :smiley:,
You can watch the repository to get notifications on the traductions and comment them if you want

**Comment by podefr** [comment]
Salut Sean, merci pour ton aide!

En dehors des tâches de traduction (auxquelles tu peux participer), nous avons besoin d'aide pour:
- Publier des documents sur medium/twitter
- Savoir lorsqu'il y a de nouveaux documents à traduire (weekly iojs, website docs...)
- Sûrement d'autres choses que j'oublie

Je t'envoie une invitation à rejoindre le groupe et te laisserai ajouter ton nom au README.md. Je fermerai ce ticket lorsque ce sera fait.

Merci!

**Comment by podefr** [comment]
Bienvenue!

**Comment by snostorm** [comment]
Merci @podefr!

> Savoir lorsqu'il y a de nouveaux documents à traduire (weekly iojs, website docs...)

Je vais commencer par aider ici. Comme je développe i18n pour tous les groupes avec [iojs/website](https://github.com/iojs/website), ce est un bon endroit pour moi.
