### ISSUE TITLE
Traduction de iojs Week of March 6th 2015

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#39]
Nous avons besoin d'une traduction pour [IO.js Week of March 6th 2015](https://medium.com/node-js-javascript/io-js-week-of-march-6th-2f9344688277). 

La traduction peut être postée en réponse à ce ticket, elle sera ensuite postée sur les réseaux sociaux listés ici #2

**Comment by Schmoopiie** [comment]
Je vais pouvoir la faire en fin de semaine. Je ferai une PR :smile:

**Comment by podefr** [comment]
Merci pour les traductions! Pourrais-tu également les publier sur twitter/medium en suivant les guidelines indiquées dans le README.md? Tiens-moi au jus si tu n'as pas les identifiants, je te les enverrai par email.

**Comment by Schmoopiie** [comment]
Je n'ai pas les identifiants.. Schmoopiie@gmail.com

Merci :smile:
