### ISSUE TITLE
Compte Twitter iojs-fr

### ISSUE THREAD

**Issue by podefr** [iojs/iojs-fr#4]
Je m'occupe de créer le compte Twitter français, contactez-moi pour avoir le mot de passe!

**Comment by thaume** [comment]
Il y en a déjà un en fait, peut être devrions nous contacter le créateur?

Le dim. 8 févr. 2015 00:26, Olivier Scherrer <notifications@github.com> a
écrit :

**Comment by podefr** [comment]
En effet, je m'en occupe

**Comment by podefr** [comment]
Lorsque vous faites partie de l'équipe de traduction, contactez [@iojs_fr](https://twitter.com/iojs_fr) afin d'obtenir le mot de passe!
