### ISSUE TITLE
Subtree?

### ISSUE THREAD

**Issue by snostorm** [iojs/iojs-fr#40]
Avec `iojs-no`, nous testons "git subtrees". Cela nous laisse pousser / tirer de leur repo à `content/no` en [iojs/website](https://github.com/iojs/website).

https://github.com/iojs/website/issues/136#issuecomment-76846668 - détails techniques

Est le groupe français prêts à essayer ce trop?

(en: I've been testing git subtrees for linking content between `iojs-no` and their `content/no` folder in the https://github.com/iojs/website repo. Any interest in helping us test this approach?)

**Comment by yoannmoinet** [comment]
Ok, ça m'a pris du temps pour comprendre :smile:
Ce serait effectivement une bonne idée.
Je suis pour :+1:

**Comment by podefr** [comment]
je n'ai pas d'expérience avec git subtree mais ok pour essayer!

**Comment by Nicolab** [comment]
Ok aussi

**Comment by snostorm** [comment]
Je ai ajouté une nouvelle branche: https://github.com/iojs/iojs-fr/tree/website

**Comment by snostorm** [comment]
Aussi https://github.com/iojs/iojs-fr/pull/44 pour le premier changement

**Comment by snostorm** [comment]
On https://github.com/iojs/website I ran this and pushed to master:

```
git rm -fr content/fr
git commit -m "Removes content/fr to allow for subtree"

git remote add -f iojs-fr git@github.com:iojs/iojs-fr.git
git merge --squash -s ours --no-commit iojs-fr/website
git read-tree --prefix=content/fr/ -u iojs-fr/website

git commit -m "Adds iojs-fr content from iojs/iojs-fr#website"
````

Now if we want to create a PR with new changes on iojs/website (either from the real branch or your own fork) given the latest version of https://github.com/iojs/iojs-fr/tree/website

```
git fetch iojs-fr website
git pull --squash -s subtree iojs-fr website
git commit -m "Updates iojs-fr content from iojs/iojs-fr#website"
```

Note: this assumes you've locally run `git remote add -f iojs-fr git@github.com:iojs/iojs-fr.git` otherwise you'd need to refer to a non-aliased git path or your own local reference.

**Comment by Nicolab** [comment]
@snostorm Excellent, thank you very much! :santa:

**Comment by snostorm** [comment]
Glad to help. Next step is probably to document this somewhere (especially the "making a PR" steps)

**Comment by yoannmoinet** [comment]
Je close ceci, pour laisser la place à l'issue pour la documentation.
