### ISSUE TITLE
Nouvelle page d'accueil

### ISSUE THREAD

**Issue by snostorm** [iojs/iojs-fr#41]
https://github.com/iojs/website/pull/276 is going to be retiring the `index.md` although it will continue to be supported.

With https://github.com/iojs/website/blob/264_build_process_2/source/templates/home.html it will no longer be required for each localization to have an `index.md` just new variables seen in that template or
https://github.com/iojs/website/blob/264_build_process_2/content/en/template.json

I'm going to try making this translation for us (with is 99% moving over the existing one). Just opening an issue here to remember.

**Comment by snostorm** [comment]
Might be a good excuse to sync up content between projects using https://github.com/iojs/iojs-fr/issues/40 ?

**Comment by yoannmoinet** [comment]
Let me know when you've done your translation, I'll proof-read it.
Thanks for your help !

**Comment by snostorm** [comment]
https://github.com/iojs/iojs-fr/issues/44 is up
