### ISSUE TITLE
Traduction de iojs Week of March 20th 2015

### ISSUE THREAD

**Issue by yoannmoinet** [iojs/iojs-fr#45]
Nous avons besoin d'une traduction pour [IO.js Week of March 20th 2015](https://medium.com/node-js-javascript/io-js-1-6-release-1df38cf64e6c).

Si personne ne s'en occupe d'ici ce week end, je pourrais m'en occuper.

Merci.

**Comment by yoannmoinet** [comment]
Je vais m'en occuper.

**Comment by podefr** [comment]
Merci pour la traduction Yoann!
