### ISSUE TITLE
Traduction de iojs Week of March 27th 2015

### ISSUE THREAD

**Issue by yoannmoinet** [iojs/iojs-fr#49]
Nous avons besoin d'une traduction pour [IO.js Week of March 27th 2015](https://medium.com/node-js-javascript/io-js-week-of-march-27th-9555f36bbb9a).

Merci.

**Comment by yoannmoinet** [comment]
je suis en train de la faire.

**Comment by yoannmoinet** [comment]
Y a-t-il quelqu'un qui peut faire un review de ça...
On est vraiment à la bourre, et personne n'a l'air de vouloir participer.

**Comment by thaume** [comment]
Je regarde !

**Comment by thaume** [comment]
Voilà, deux petits points très peu importants :) tu as accès au medium ?

**Comment by podefr** [comment]
Désolé j'ai mergé alors que tu postais tes commentaires :( Est-ce qu'on fait un nouveau pull request avec les modifs?

**Comment by thaume** [comment]
Non ce n'était rien de très important ;)

**Comment by yoannmoinet** [comment]
Merci !

**Comment by yoannmoinet** [comment]
Je n'ai pas les accès à Medium ou Twitter par contre. 
Quelqu'un d'autre devra le poster je pense.

**Comment by podefr** [comment]
Je t'envoie un mail sur ton adresse gmail avec les identifiants (d'ici quelques heures), ensuite tu peux juste suivre les indications sur le Readme du projet.
