### ISSUE TITLE
Traduction de la tagline iojs

### ISSUE THREAD

**Issue by thaume** [iojs/iojs-fr#5]
La tagline des comptes twitter/medium d'iojs est "Bringing ES6 to the Node Community!"

Que pensez-vous de "L'arrivée d'ES6 pour la communauté Node francophone !" comme trad ?

**Comment by podefr** [comment]
ok pour moi!

**Comment by bentranter** [comment]
ok pour moi aussi!

**Comment by oncletom** [comment]
Nope, *bringing* c'est une action. Genre "io.js apporte ES6 à la communauté Node".

**Comment by thaume** [comment]
Tout à fait d'accord, je voulais juste ne pas réutiliser le sujet

**Comment by oncletom** [comment]
Oui je comprends. *L'arrivée d'ES6* ne signifie pas la même chose et ça sonne faux à l'oreille.

Ça peut très bien se simplifier en *ES6 pour la communauté Node*. Ce qui traduit l'intention sur le long-terme alors qu'*arrivée* se focalise sur un instant-T, maintenant.

**Comment by thaume** [comment]
Ta dernière formule, "ES6 pour la communauté Node", me plait bien ! Qu'en pensent les autres ?

**Comment by podefr** [comment]
Oui c'est encore mieux, je suis pour aussi!

**Comment by bcabanes** [comment]
+1 pour "ES6 pour la communauté Node"

**Comment by podefr** [comment]
j'ai mis twitter et medium à jour avec la dernière proposition
