### ISSUE TITLE
Traduction de iojs Week of April 3rd 2015

### ISSUE THREAD

**Issue by yoannmoinet** [iojs/iojs-fr#51]
Nous avons besoin d'une traduction pour [IO.js Week of April 3rd 2015](https://medium.com/node-js-javascript/io-js-week-of-april-3rd-a4e1fe0c38c1).

Merci.

**Comment by podefr** [comment]
Je peux m'en occuper demain au plus tôt

**Comment by podefr** [comment]
Je viens de créer #52, merci de relire/approuver :)

**Comment by yrezgui** [comment]
J'ai fait une review.
