### ISSUE TITLE
Traducteur

### ISSUE THREAD

**Issue by yrezgui** [iojs/iojs-fr#8]
Salut les gars,

J'ai demandé à rejoindre la team des traducteurs ici: https://github.com/iojs/website/issues/125#issuecomment-73385695

et Mikeal me l'a confirmé ici: https://github.com/iojs/website/issues/125#issuecomment-73386084

Je crée donc cette issue pour rejoindre la team et aider la team FR :)

**Comment by podefr** [comment]
Bienvenue Yacine! Je crois qu'il faut d'abord que tu acceptes l'invitation GitHub à rejoindre la team. La page settings pour ce repository t'indique en "pending".

Lorsque tu auras accès, n'oublies pas d'ajouter ton nom au README.md dans la partie Membres!

**Comment by yrezgui** [comment]
J'ai pas reçu de mails...
![screen shot 2015-02-09 at 15 01 55](https://cloud.githubusercontent.com/assets/1113976/6108641/b72c2f12-b06c-11e4-9a29-90a6cb28b29f.png)

**Comment by podefr** [comment]
Regarde tes spams peut-être? Je t'ai renvoyé une invitation il y a quelques minutes

**Comment by yrezgui** [comment]
Snif, toujours rien (spam vérifié)

**Comment by yrezgui** [comment]
Dernier update, j'ai pu accepté l'invitation en la trouvant sur la page de l'organisation https://github.com/iojs mais jamais eu de mail. Bref, problème réglé :)

Je me suis ajouté à la liste des membres: https://github.com/iojs/iojs-fr/pull/13

**Comment by podefr** [comment]
ouf ;) j'ai mergé #13
