### ISSUE TITLE
Traduction du site

### ISSUE THREAD

**Issue by pierreinglebert** [iojs/iojs-fr#9]
Voici où ça se passe : https://github.com/iojs/website/tree/i18n-static/public/i18n/fr

Des volontaires ?
Comment s'organise-t-on ?

**Comment by thaume** [comment]
Mmm on peut créer des pull requests et les référencer dans ce thread, comme ça on peut en parler entre nous?
En plus n'importe qui pourra rajouter des commentaires directement sur le fichier de PR, la personne ayant lancé la PR pourra rajouter ou non ces commentaires dans le fichier traduit.

**Comment by yrezgui** [comment]
Petite question. On référence plutôt les liens vers la doc fr ou en de MDN ? J'ai parfois trouvé la documentation française incomplète.

**Comment by thaume** [comment]
Le [fr] en priorité j'imagine, avec un second lien vers le [en] peut-être ? Après il faut voir à quel point on prend les gens par la main, quelqu'un d'intéressé ira voir les docs [en], quelque de non intéressé se satisfera des docs [fr] (même incomplètes). Un avis ?

**Comment by podefr** [comment]
Je pense effectivement qu'il faudra référencer la page FR en priorité, ça incitera la communauté à étoffer les documentations incomplètes, quitte à ajouter également un lien vers la page en version originale.

Je veux bien m'occuper de traduire la page es6.html, je fais une proposition en fin de journée.

**Comment by pierreinglebert** [comment]
Attention, les fichiers viennent de bouger, ils sont en markdown ici : https://github.com/iojs/website/tree/master/content/fr

**Comment by podefr** [comment]
je crois que les actions nécessaires sont en cours ou terminées, peut-on fermer ce ticket?
